remove double-quotes

diff --git a/functions/command_check b/functions/command_check
--- a/functions/command_check
+++ b/functions/command_check
@@ -4,7 +4,7 @@
 command_check() {
   for cmd in "$@"; do
     if ! command -v "$cmd" >/dev/null 2>&1; then
-      printf "%s\n" "Error: Required command "$cmd" not found. Exiting." >&2
+      printf "%s\n" "Error: Required command $cmd not found. Exiting." >&2
       exit 1
     fi
 done
