capitalize

diff --git a/functions/permission_check b/functions/permission_check
--- a/functions/permission_check
+++ b/functions/permission_check
@@ -4,7 +4,7 @@
 # If user's UID is not 0, redirect output to standard error, then exit.
 root_check() {
   if [ "$EUID" -ne "0" ] ; then
-    printf "%s\n" "Error: root privileges are required to continue. Exiting." >&2
+    printf "%s\n" "Error: Root privileges are required to continue. Exiting." >&2
     exit 1
   fi
 }
