refactor command_check function in line with unit test

diff --git a/src/power_UPS b/src/power_UPS
--- a/src/power_UPS
+++ b/src/power_UPS
@@ -3,14 +3,15 @@
 
 script=$(basename "$0")
 program="power_UPS"
-
 data_file="ups_data.csv"
 
 command_check() {
   for cmd in "$@"; do
-    command -v "$cmd" >/dev/null 2>&1 ||
-      { printf "%s\n" >&2 "'$cmd' not detected. Exiting."; exit 1; }
-  done
+    if ! command -v "$cmd" >/dev/null 2>&1; then
+      printf "%s\n" "Error: Required command "$cmd" not found. Exiting." >&2
+      exit 1
+    fi
+done
 }
 
 data_file_check() {
